### PR TITLE
improve coag gain calculation

### LINKED ISSUE #138: followup on PR #136
Issues to address during/after #136 

- [x] fix bug in coag gain calculation
- [ ] explain areas to improve (getting rid of the for loop for example + adding more rigorous stuff for the trimming)
- [x] documenting the methodology clearly
- [ ] explain how an alternative methodology can be implemented using discrete math (this is the continuous math solution to the problem)

### LINKED ISSUE #148: improve coagulation kernel calculation even more
In #141, a decent coag gain calculation looks like this:

https://github.com/uncscode/particula/blob/8b48cf14c7a7ee9b030babc63cfb5d5e83569209/particula/util/coagulation_rate.py#L91-L129

For simplicity,

```python
nums, rads, kern = self.coag_prep() 
gain = np.zeros_like(rads) 

interp = RectBivariateSpline(rads.m, rads.m, kern.m) 
  
for i, dpa in enumerate(rads):   

    dpd = np.linspace(0, dpa.m/2**(1/3), rads.m.size)*rads.u 
    dpi = (dpa**3 - dpd**3)**(1/3) 

    num_rep = np.interp(dpd, rads, nums) 
    num_oth = np.interp(dpi, rads, nums) 
    ker_oth = interp.ev(dpi.m, dpd.m) * kern.u 

    dss = (dpa**3 - dpd**3)**(2/3) 
  
    test = (dpa**2)*np.trapz(ker_oth*num_oth*num_rep/dss, dpd) 
  
    gain[i] = test.m   
return gain*test.u 
```

Two bottlenecks: the for-loop and the interp.

1. this refactoring will likely help a bit:
```diff
- interp = RectBivariateSpline(rads.m, rads.m, kern.m) 
+ interp = RectBivariateSpline(rads.m, rads.m, kern.m * nums.m * np.tranpose(nums.m))   

...

-   num_rep = np.interp(dpd, rads, nums) 
-   num_oth = np.interp(dpi, rads, nums) 
-   ker_oth = interp.ev(dpi.m, dpd.m) * kern.u
+   knn = interp.ev(dpi.m, dpd.m) 
```

2. get rid of for-loop with something with something like this (but need to verify everything works:
```python

gain = np.zeros_like(rads)

interp = RectBivariateSpline(rads.m, rads.m, kern.m * nums.m * np.tranpose(nums.m))

dpd = np.linspace(0, rads.m/2**(1/3), rads.m.size)*rads.u
dpi = (rads**3 - dpd**3)**(1/3)

gain = rads**2 * np.trapz( 
    interp.ev(dpi.m, dpd.m) * kern.u * num.u * num.u / dpi**2, dpd
)
```

### PR DESCRIPTION
**Pull request by ngam**
Fixes #138 
Fixes #148 

<details>
sketchy matlab code snippet from back in the day... as a guidance to resolve the bug, I am aging and thus unable to be creative about algorithms...

```matlab

coagLossRates(11,:) = bsxfun(@times, ...
  particleNumberDistributionFractioned(11,:),...
  (1e6).*trapz(particleDiameter_nm, ...
  bsxfun(@times,coagK25at,particleNumberDistributionFractioned(1 ,:))+...
  bsxfun(@times,coagK20at,particleNumberDistributionFractioned(2 ,:))+...
  bsxfun(@times,coagK15at,particleNumberDistributionFractioned(3 ,:))+...
  bsxfun(@times,coagK10at,particleNumberDistributionFractioned(4 ,:))+...
  bsxfun(@times,coagK5at ,particleNumberDistributionFractioned(5 ,:))+...
  bsxfun(@times,coagK0   ,particleNumberDistributionFractioned(6 ,:))+...
  bsxfun(@times,coagK5re ,particleNumberDistributionFractioned(7 ,:))+...
  bsxfun(@times,coagK10re,particleNumberDistributionFractioned(8 ,:))+...
  bsxfun(@times,coagK15re,particleNumberDistributionFractioned(9 ,:))+...
  bsxfun(@times,coagK20re,particleNumberDistributionFractioned(10,:))+...
  bsxfun(@times,coagK25re,particleNumberDistributionFractioned(11,:)),2)');


% brute force calculations of the coagulation gain rate
% using a double trapz-interp2 estimation
% (very accurate but costly)
% replace interp2 by manual matrix of upper/lower bounds
% see updated file

coagGainRates = zeros(11,length(dp));


[dp1, dp2] = meshgrid(particleDiameter_nm);


coagGainRates(1,:) =  bsxfun(@times,.5.*(particleDiameter_nm.^2),(...
  trapz(particleDiameter_nm,...
    triu(interp2(dp1,dp2,(1e6).*coagK0.*...
      bsxfun(@times,particleNumberDistributionFractioned(1,:),...
        particleNumberDistributionFractioned(6,:)'),...
          dp2,(bsxfun(@minus, diag(dp2)'.^3 ,triu(dp2,1).^3)).^(1/3),  ...
'spline')./(bsxfun(@minus,diag(dp2)'.^3,triu(dp2,1).^3) ).^(2/3),1)) +...
  trapz(particleDiameter_nm,...
    triu(interp2(dp1,dp2,(1e6).*coagK5re.*...
      bsxfun(@times,particleNumberDistributionFractioned(2,:),...
        particleNumberDistributionFractioned(5,:)'),...
          dp2,(bsxfun(@minus, diag(dp2)'.^3 ,triu(dp2,1).^3)).^(1/3),  ...
'spline')./(bsxfun(@minus,diag(dp2)'.^3,triu(dp2,1).^3) ).^(2/3),1)) +...
  trapz(particleDiameter_nm,...
    triu(interp2(dp1,dp2,(1e6).*coagK6re.*...
      bsxfun(@times,particleNumberDistributionFractioned(3,:),...
        particleNumberDistributionFractioned(4,:)'),...
          dp2,(bsxfun(@minus, diag(dp2)'.^3 ,triu(dp2,1).^3)).^(1/3),  ...
'spline')./(bsxfun(@minus,diag(dp2)'.^3,triu(dp2,1).^3) ).^(2/3),1)) +...
  trapz(particleDiameter_nm,...
    triu(interp2(dp1,dp2,(1e6).*coagK6re.*...
      bsxfun(@times,particleNumberDistributionFractioned(4,:),...
        particleNumberDistributionFractioned(3,:)'),...
          dp2,(bsxfun(@minus, diag(dp2)'.^3 ,triu(dp2,1).^3)).^(1/3),  ...
'spline')./(bsxfun(@minus,diag(dp2)'.^3,triu(dp2,1).^3) ).^(2/3),1)) + ...
  trapz(particleDiameter_nm,...
    triu(interp2(dp1,dp2,(1e6).*coagK5re.*...
      bsxfun(@times,particleNumberDistributionFractioned(5,:),...
        particleNumberDistributionFractioned(2,:)'),...
          dp2,(bsxfun(@minus, diag(dp2)'.^3 ,triu(dp2,1).^3)).^(1/3),  ...
'spline')./(bsxfun(@minus,diag(dp2)'.^3,triu(dp2,1).^3) ).^(2/3),1)) +...
  trapz(particleDiameter_nm,...
    triu(interp2(dp1,dp2,(1e6).*coagK0.*...
      bsxfun(@times,particleNumberDistributionFractioned(6,:),...
        particleNumberDistributionFractioned(1,:)'),...
          dp2,(bsxfun(@minus, diag(dp2)'.^3 ,triu(dp2,1).^3)).^(1/3),  ...
'spline')./(bsxfun(@minus,diag(dp2)'.^3,triu(dp2,1).^3) ).^(2/3),1))));


```

I guess the keys are:
- need to mesh the aux dps
- need to fine-tune interp
- need to thoroughly test this on smaller cases
- ughhhhhhh
- beautiful code tho

</details>

### CODE REVIEW

**Comment by ngam** [comment]
@Gorkowski, this is ready in case you need to do something with it. Now this looks 100% correct. Only thing we can do from now on is to optimize this calculation --- I think we can still squeeze better performance out of that embarrassing loop...

number density rates:
Screen Shot 2022-02-26 at 16 46 38

volume density rates (integrating the dotted black curve should yield ~zero)
Screen Shot 2022-02-26 at 16 44 51

**Comment by ngam** [comment]
> @Gorkowski I believe we are more or less done with the hard and annoying parts. Next:
> 
> 1. need a decent solver (I will start shopping for one or I can just write one myself; I actually prefer the latter because then we can fine-tune it for our exact needs, etc.)
> 2. need to fill in some science gaps (e.g. add condensation, nucleation, etc. --- all relatively easier than coagulation)
> 3. need to start adding options (e.g. other coagulation kernels, etc.)
> 4. NEED TO START DOING ACTUAL SCIENCE!
> 
> I am not really in a creative headspace when it comes to this nowadays, so I will definitely need your help/motivation for 4. For the rest, I got you as I will just need to rewrite stuff slightly differently. I just don't have any specific ideas to pursue at the moment, so start thinking of actual science needs and I can do the technical stuff to make it happen.
> 
> (A distant goal: 5. add chemistry, species, etc. --- this is something that will be relatively new to me... so it will take some time)

@Gorkowski I updated the algorithm again, sorry... this is much better now lol, I believe with a speedup of 100x or so

**Comment by ngam** [comment]
unless you want me to add anything else to this, I am going to merge it soonish.

**Review by Gorkowski — APPROVED** [review]
nice speed up

**Pull request merged**
