### PR TITLE
documenting building particula better

### LINKED ISSUE #114: documenting building particula better

### PR DESCRIPTION
**Pull request by ngam**
Fixes #114

No major changes or edits, just slightly better documenting building particula as an editable package through `pip install -e ".[dev]"`

Highlights:
- removed requirements file completely (no need)
- added documentation for `pip install -e ".[dev]"` instead
- adjusted workflows to reflect new changes

Notes:
- `-e` is for `--editable` implying the package is continuously self-updating to reflect local changes in source code (in the repository)
- this means the edits will be seen globally without the need to keep moving between folders
- `".[dev]"`: the quotes are because some systems (e.g. macOS) will fail without them, and `[dev]` instructing `pip` to install the extra dependencies defined in setup.cfg subsection `dev` of section `[options.extras_require]=`
- there is a known bug in `-e` mode vis-a-vis user space; added a note about using a workaround with `--prefix=~/.local`, also adopting the same workaround in the Docker container

TODO (for later):
- make notebooks self-execute upon building to ensure they are always built with the latest version of the package

### CODE REVIEW

**Review by wkchuang — APPROVED** [review]

**Comment by ngam** [comment]
[cda06cf](https://github.com/uncscode/particula/pull/115/commits/cda06cffadcc14c34acf327f46b7cb505645849c) fixes the issue of installing `particular` _without_ reps in the container.

**Comment by wkchuang** [comment]
particular <-> particula? just making sure we're not talking about different things

**Comment by ngam** [comment]
> particular <-> particula? just making sure we're not talking about different things

Yes, sorry, `PARTICULA!` 😵‍💫

**Comment by ngam** [comment]
Should probably update pip too... just a second

**Review by wkchuang — APPROVED** [review]

**Review by wkchuang — APPROVED** [review]

**Comment by ngam** [comment]
Sorry, I was testing it again and gain to make sure things work smoothly in the container...

**Review by wkchuang — APPROVED** [review]

**Comment by ngam** [comment]
Taking this into a new issue:

TODO (for later):

- make notebooks self-execute upon building to ensure they are always built with the latest version of the package

**Pull request merged**
