### PR TITLE
fix radius_cutoff

### LINKED ISSUE #207: allow multi mode dists
allow for kwargs like the following

multi_mode = {
    "mode": [5000e-9, 50e-9, 300e-9], # coarse, nano, fine mode
    "nbins": 1000, # 1000 bins
    "nparticles": [1e6,1e9,1e7], # 1e4 #
    "volume": 1e-6, # per 1e-6 m^3 (or 1 cc)
    "gsigma": [1.5,1.2,1.5], # 
    "spacing": "logspace", # bin spacing, 
}

### PR DESCRIPTION
**Pull request by ngam**
fixes #207 

Todo:
- [x] fix radius_cutoff
- [x] fix distribution
- [x] test

### CODE REVIEW

**Comment by ngam** [comment]
@Gorkowski this is more or less ready, could you have a look and think of an appropriate test?

**Comment by ngam** [comment]
To clarify, a test or two are needed in particle_test.py.

**Review by Gorkowski — APPROVED** [review]
looking good to me :)

**Comment by ngam** [comment]
Thanks!!! @Gorkowski

nice testing

**Pull request merged**
