### PR TITLE
add solver

### LINKED ISSUE #142: add a proper solver
need two types of solvers in general:
1. simple time-based ODE solvers
2. a more complicated PDE solver for the GDE

### PR DESCRIPTION
**Pull request by ngam**
Fixes #142

### CODE REVIEW

**Comment by ngam** [comment]
I will get to this today afternoon hopefully.

**Comment by ngam** [comment]
<details>
<summary> reference: </summary>

```
        updateParticleNumberDistributionFractioned(:,1:end-1) = ...
            particleNumberDistributionFractioned(:,1:end-1) - ...
            (timeStep./sizeStep(1)).*...
            (numericalFlux(:,2:end)-numericalFlux(:,1:end-1)) + ...
            timeStep.*(gDiscC(:,1:end-1)+gDiscC(:,1:end-1))./2;

        updateParticleNumberDistributionFractioned(:,end) = ...
            particleNumberDistributionFractioned(:,end) - ...
            (timeStep./sizeStep(end)).*...
            (0-numericalFlux(end)) + ...
            timeStep.*(gDiscC(:,end));
```

--> dn/dt = - Δ(nf)/Δd + g 
where n(t=0) = n0, f[1:] = cond, g = sink, etc.
but (fn)[0] = nucleation 
then: Δ(nf)[0:-1]/Δd = ( (fn)[1:]-(fn)[0:-1] )/ Δd and Δ(nf)[-1]/Δd = (0 - nf[-1])/Δd
</details>

**Review by Gorkowski — APPROVED** [review]
I like this, we can add complexity as things expand.

**Comment by ngam** [comment]
thanks @Gorkowski

**Pull request merged**
